#!/usr/bin/env node
// Generated by scripts/bundle-termux-engine.mjs — do not edit by hand.
// Source: src/lib/planner/termux-entry.ts (+ engine/goals/behavior/contract/tools/types).
// Runs the deterministic Stone* Planner engine as a standalone REST service.

import { createServer } from "node:http";
import { existsSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
//#region src/lib/planner/contract.ts
function statusOf(engine, date) {
	return {
		ok: true,
		version: engine.version,
		app: "stone-star-planner",
		date,
		nextActionId: engine.nextActions[date] ?? null,
		plans: Object.keys(engine.plans).length,
		goals: engine.goals.length,
		attempts: engine.attempts.length,
		updatedAt: engine.updatedAt
	};
}
//#endregion
//#region src/lib/planner/goals.ts
function defaultGoals(now = /* @__PURE__ */ new Date()) {
	const t = now.toISOString();
	return [
		{
			id: "dsa",
			title: "DSA instruction + problems",
			source: "dsa",
			kind: "curriculum",
			dataRef: "dsa-plan",
			weeklyTarget: {
				sessions: 5,
				minutes: 450
			},
			defaultDuration: 90,
			priority: 1,
			active: true,
			createdAt: t,
			updatedAt: t
		},
		{
			id: "english",
			title: "English fluency lessons",
			source: "english",
			kind: "curriculum",
			dataRef: "english-plan",
			weeklyTarget: {
				sessions: 6,
				minutes: 300
			},
			defaultDuration: 50,
			priority: 2,
			active: true,
			createdAt: t,
			updatedAt: t
		},
		{
			id: "smm",
			title: "SMM interview prep",
			source: "smm",
			kind: "curriculum",
			dataRef: "smm-questions",
			weeklyTarget: {
				sessions: 3,
				minutes: 90
			},
			defaultDuration: 30,
			priority: 2,
			active: true,
			createdAt: t,
			updatedAt: t
		},
		{
			id: "fullstack",
			title: "Fullstack practice round",
			source: "fullstack",
			kind: "curriculum",
			dataRef: "questions",
			weeklyTarget: {
				sessions: 3,
				minutes: 120
			},
			defaultDuration: 40,
			priority: 3,
			active: true,
			createdAt: t,
			updatedAt: t
		}
	];
}
function slugify(title) {
	return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 32) || "task";
}
function makeAdHocGoal(input, now = /* @__PURE__ */ new Date()) {
	const t = now.toISOString();
	const stamp = `${Date.now().toString(36)}`;
	return {
		id: `custom:${slugify(input.title)}:${stamp}`,
		title: input.title,
		source: "custom",
		kind: "task",
		defaultDuration: Math.min(480, Math.max(10, input.durationMinutes ?? 30)),
		priority: input.priority ?? 2,
		deadline: input.deadline,
		project: input.project,
		active: true,
		createdAt: t,
		updatedAt: t
	};
}
function upsertGoal(goals, goal) {
	const idx = goals.findIndex((g) => g.id === goal.id);
	if (idx === -1) return [...goals, goal];
	const next = [...goals];
	next[idx] = {
		...next[idx],
		...goal,
		updatedAt: (/* @__PURE__ */ new Date()).toISOString()
	};
	return next;
}
function activeGoals(goals) {
	return goals.filter((g) => g.active);
}
function setWeeklyTarget(goals, goalId, target) {
	return goals.map((g) => g.id === goalId ? {
		...g,
		weeklyTarget: target,
		updatedAt: (/* @__PURE__ */ new Date()).toISOString()
	} : g);
}
function setGoalActive(goals, goalId, active) {
	return goals.map((g) => g.id === goalId ? {
		...g,
		active,
		updatedAt: (/* @__PURE__ */ new Date()).toISOString()
	} : g);
}
//#endregion
//#region src/lib/planner/behavior.ts
const MIN_ATTEMPTS_FOR_TRUST = 5;
const MIN_ATTEMPTS_FOR_SLOT = 2;
function hourOf(timeOfDay) {
	const [h] = timeOfDay.split(":").map(Number);
	return Number.isFinite(h) ? h : 12;
}
function binLabel(hour) {
	const h = hour % 24;
	return `${String(h).padStart(2, "0")}:00`;
}
function computeBehavior(attempts) {
	const byGoal = /* @__PURE__ */ new Map();
	for (const a of attempts) {
		const list = byGoal.get(a.goalId) ?? [];
		list.push(a);
		byGoal.set(a.goalId, list);
	}
	const out = {};
	for (const [goalId, list] of byGoal) {
		if (!list.length) continue;
		const completedList = list.filter((a) => a.completed);
		const totalMinutes = list.reduce((s, a) => s + a.actualMinutes, 0);
		const avgDuration = Math.round(totalMinutes / list.length);
		const successRate = list.filter((a) => a.completed).length / list.length;
		const byHour = /* @__PURE__ */ new Map();
		for (const a of list) {
			const h = hourOf(a.timeOfDay);
			const cur = byHour.get(h) ?? {
				n: 0,
				ok: 0
			};
			cur.n += 1;
			if (a.completed) cur.ok += 1;
			byHour.set(h, cur);
		}
		let bestSlot = null;
		let bestScore = -1;
		for (const [h, v] of byHour) {
			if (v.n < MIN_ATTEMPTS_FOR_SLOT) continue;
			const score = v.ok / v.n + Math.min(v.n, 6) / 60;
			if (score > bestScore) {
				bestScore = score;
				bestSlot = binLabel(h);
			}
		}
		out[goalId] = {
			goalId,
			attempts: list.length,
			completed: completedList.length,
			avgDuration,
			bestSlot,
			successRate,
			updatedAt: list[list.length - 1]?.createdAt ?? (/* @__PURE__ */ new Date()).toISOString()
		};
	}
	return out;
}
/** Learned duration once we trust the sample, else the goal's default. */
function suggestDuration(goal, behavior) {
	const s = behavior[goal.id];
	if (s && s.attempts >= MIN_ATTEMPTS_FOR_TRUST && s.avgDuration > 0) return Math.min(240, s.avgDuration);
	return goal.defaultDuration;
}
/** Best slot once we have signal, else null (engine falls back to priority order). */
function suggestSlot(goal, behavior) {
	return behavior[goal.id]?.bestSlot ?? null;
}
//#endregion
//#region src/lib/planner/engine.ts
function toMin(t) {
	const [h, m] = t.split(":").map(Number);
	return (Number.isFinite(h) ? h : 0) * 60 + (Number.isFinite(m) ? m : 0);
}
function toTime(min) {
	const h = Math.floor(min / 60);
	const m = min % 60;
	return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`;
}
const DEFAULT_AVAILABILITY = {
	dayStart: "07:00",
	dayEnd: "21:00",
	blocked: [{
		start: "10:00",
		end: "14:30",
		label: "College"
	}]
};
function freeWindows(availability = DEFAULT_AVAILABILITY) {
	const dayStart = toMin(availability.dayStart);
	const dayEnd = toMin(availability.dayEnd);
	const blocked = [...availability.blocked].map((c) => ({
		start: Math.max(dayStart, toMin(c.start)),
		end: Math.min(dayEnd, toMin(c.end))
	})).filter((c) => c.end > c.start).sort((a, b) => a.start - b.start);
	const merged = [];
	for (const c of blocked) {
		const last = merged[merged.length - 1];
		if (last && c.start <= last.end) last.end = Math.max(last.end, c.end);
		else merged.push({ ...c });
	}
	const windows = [];
	let cursor = dayStart;
	for (const m of merged) {
		if (m.start > cursor) windows.push({
			start: toTime(cursor),
			end: toTime(m.start)
		});
		cursor = Math.max(cursor, m.end);
	}
	if (cursor < dayEnd) windows.push({
		start: toTime(cursor),
		end: toTime(dayEnd)
	});
	return windows;
}
function dateIso(offset = 0) {
	const d = /* @__PURE__ */ new Date();
	d.setHours(0, 0, 0, 0);
	d.setDate(d.getDate() + offset);
	return d.toISOString().slice(0, 10);
}
function nowTime() {
	const d = /* @__PURE__ */ new Date();
	return `${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`;
}
function makeBlock(goal, start, minutes, status, why) {
	return {
		id: `${goal.id}:${start.replace(":", "")}:${Date.now().toString(36)}`,
		goalId: goal.id,
		title: goal.title,
		start,
		end: toTime(toMin(start) + minutes),
		minutes,
		status,
		priority: goal.priority,
		why,
		attemptIds: []
	};
}
function blockById(plan, blockId) {
	return plan?.blocks.find((b) => b.id === blockId);
}
function sortForScheduling(goals) {
	return [...goals].sort((a, b) => {
		if (a.priority !== b.priority) return a.priority - b.priority;
		if (a.deadline && b.deadline && a.deadline !== b.deadline) return a.deadline.localeCompare(b.deadline);
		return b.defaultDuration - a.defaultDuration;
	});
}
function scheduleGoal(goal, windows, behavior, current) {
	const duration = Math.min(suggestDuration(goal, behavior), 180);
	if (duration <= 0) return null;
	for (const w of windows) {
		const wStart = toMin(w.start);
		const wEnd = toMin(w.end);
		const used = current.filter((b) => toMin(b.start) >= wStart && toMin(b.end) <= wEnd).reduce((s, b) => s + b.minutes, 0);
		if (used + duration <= wEnd - wStart) return makeBlock(goal, toTime(wStart + used), duration, "planned", engineWhy(goal, behavior));
	}
	const half = Math.floor(duration / 2);
	if (half >= 15) for (const w of windows) {
		const wStart = toMin(w.start);
		const leftover = toMin(w.end) - wStart;
		if (leftover >= half + 5) return makeBlock(goal, toTime(wStart + leftover - half), half, "planned", "Split into a focused mini-session (scope reduced).");
	}
	return null;
}
function engineWhy(goal, behavior) {
	const parts = [`P${goal.priority}`];
	const slot = suggestSlot(goal, behavior);
	if (slot) parts.push(`best time ~${slot}`);
	if (goal.deadline) parts.push(`deadline ${goal.deadline}`);
	const wt = goal.weeklyTarget;
	if (wt) parts.push(`${wt.sessions}x/wk`);
	return parts.length ? parts.join(" · ") : "Priority order";
}
function planDay(input) {
	const windows = freeWindows(input.availability);
	const prev = input.previous;
	const blocks = [];
	if (prev) for (const b of prev.blocks) {
		if (b.status === "done" || b.status === "skipped" || b.status === "carried") continue;
		const goal = input.goals.find((g) => g.id === b.goalId);
		if (!goal || !goal.active || b.minutes <= 0) continue;
		const slot = scheduleGoal(goal, windows, input.behavior, blocks);
		if (slot) blocks.push({
			...slot,
			sourceEvent: `${b.status} carry`,
			why: `${slot.why} · carried from ${prev.date}`
		});
		else carryAsCompressed(goal, windows, blocks, b);
	}
	const ordered = sortForScheduling(activeGoals(input.goals));
	for (const goal of ordered) {
		if (blocks.some((b) => b.goalId === goal.id && b.status !== "skipped")) continue;
		const slot = scheduleGoal(goal, windows, input.behavior, blocks);
		if (slot) blocks.push(slot);
	}
	blocks.sort((a, b) => toMin(a.start) - toMin(b.start));
	return {
		date: input.date,
		blocks,
		version: 1
	};
}
function carryAsCompressed(goal, windows, blocks, original) {
	if (original.minutes < 30) return;
	const half = Math.floor(original.minutes / 2);
	const compact = {
		...makeBlock(goal, "00:00", half, "carried", "Compressed carry-over (scope reduced)."),
		start: "00:00"
	};
	for (const w of windows) {
		const wStart = toMin(w.start);
		const used = blocks.filter((b) => toMin(b.start) >= wStart && toMin(b.end) <= toMin(w.end)).reduce((s, b) => s + b.minutes, 0);
		if (used + half <= toMin(w.end) - wStart) {
			compact.start = toTime(wStart + used);
			compact.end = toTime(toMin(compact.start) + half);
			blocks.push(compact);
			return;
		}
	}
}
/** First block claiming attention for "right now". */
function nextAction(plan, now) {
	if (!plan) return null;
	const nowMin = toMin(now);
	const open = plan.blocks.filter((b) => b.status === "planned" || b.status === "active" || b.status === "carried");
	const inProgress = open.find((b) => b.status === "active");
	if (inProgress) return inProgress;
	const current = open.find((b) => nowMin >= toMin(b.start) && nowMin < toMin(b.end));
	if (current) return current;
	return open.find((b) => toMin(b.start) >= nowMin) ?? null;
}
function emptyState(goals, now = /* @__PURE__ */ new Date()) {
	return {
		version: 1,
		goals: goals ?? defaultGoals(now),
		plans: {},
		attempts: [],
		behavior: {},
		nextActions: {},
		updatedAt: now.toISOString()
	};
}
function rebuildPlan(engine, date = dateIso()) {
	const previous = engine.plans[dateIso(-1)] ?? null;
	const plan = planDay({
		date,
		goals: engine.goals,
		behavior: engine.behavior,
		previous
	});
	const action = nextAction(plan, nowTime());
	return {
		...engine,
		plans: {
			...engine.plans,
			[date]: plan
		},
		nextActions: {
			...engine.nextActions,
			[date]: action ? action.id : null
		},
		updatedAt: (/* @__PURE__ */ new Date()).toISOString()
	};
}
function applyEvent(engine, event) {
	switch (event.type) {
		case "replan": return rebuildPlan(engine);
		case "task_started": {
			const plan = engine.plans[dateIso()];
			if (!plan) return engine;
			const blocks = plan.blocks.map((b) => b.id === event.blockId ? {
				...b,
				status: "active"
			} : b);
			return recomputeNext({
				...engine,
				plans: {
					...engine.plans,
					[plan.date]: {
						...plan,
						blocks
					}
				}
			}, plan.date);
		}
		case "task_completed": {
			const plan = engine.plans[dateIso()];
			if (!plan) return engine;
			const block = blockById(plan, event.blockId);
			if (!block) return engine;
			const attempt = {
				id: `a:${event.blockId}:${Date.now().toString(36)}`,
				goalId: block.goalId,
				blockId: event.blockId,
				date: plan.date,
				plannedMinutes: block.minutes,
				actualMinutes: Math.max(1, Math.round(event.actualMinutes)),
				timeOfDay: block.start,
				completed: true,
				energy: event.feedback.energy,
				difficulty: event.feedback.difficulty,
				focus: event.feedback.focus,
				note: event.feedback.note,
				createdAt: event.at
			};
			const blocks = plan.blocks.map((b) => b.id === event.blockId ? {
				...b,
				status: "done",
				attemptIds: [...b.attemptIds, attempt.id]
			} : b);
			let next = {
				...engine,
				attempts: [...engine.attempts, attempt],
				plans: {
					...engine.plans,
					[plan.date]: {
						...plan,
						blocks
					}
				}
			};
			const behavior = computeBehavior(next.attempts);
			next = {
				...next,
				behavior
			};
			return recomputeNext(next, plan.date);
		}
		case "task_skipped": {
			const plan = engine.plans[dateIso()];
			if (!plan) return engine;
			const blocks = plan.blocks.map((b) => b.id === event.blockId ? {
				...b,
				status: "skipped",
				why: event.reason ?? "Skipped"
			} : b);
			return rebuildPlan({
				...engine,
				plans: {
					...engine.plans,
					[plan.date]: {
						...plan,
						blocks
					}
				}
			});
		}
		case "urgent_add": {
			const goal = event.goal;
			const goals = upsertGoal(engine.goals, goal);
			return rebuildPlan({
				...engine,
				goals
			}, dateIso());
		}
		case "set_goal_target": {
			const goals = setWeeklyTarget(engine.goals, event.goalId, event.weeklyTarget);
			return rebuildPlan({
				...engine,
				goals
			});
		}
		case "set_goal_active": {
			const goals = setGoalActive(engine.goals, event.goalId, event.active);
			return rebuildPlan({
				...engine,
				goals
			});
		}
		default: return engine;
	}
}
function applyEvents(engine, events) {
	let next = engine;
	for (const ev of events) next = applyEvent(next, ev);
	return next;
}
function recomputeNext(engine, date) {
	const plan = engine.plans[date];
	const action = plan ? nextAction(plan, nowTime()) : null;
	return {
		...engine,
		nextActions: {
			...engine.nextActions,
			[date]: action ? action.id : null
		},
		updatedAt: (/* @__PURE__ */ new Date()).toISOString()
	};
}
//#endregion
//#region src/lib/planner/termux-entry.ts
/**
* Termux engine entry — deterministic Planner Engine as a self-contained Node
* service. Single source of state.json, implements the REST contract in
* `contract.ts`. Bundled to `termux/planner-engine.mjs` (no npm install needed
* on the phone).
*/
const HOST = process.env.HOST ?? "0.0.0.0";
const PORT = Number(process.env.PORT ?? 8787);
const STATE_FILE = resolve(process.env.STATE_FILE ?? "state.json");
function loadStore() {
	try {
		if (existsSync(STATE_FILE)) {
			const raw = JSON.parse(readFileSync(STATE_FILE, "utf8"));
			if (raw && Array.isArray(raw.goals) && typeof raw.version === "number") return { engine: raw };
		}
	} catch {}
	const engine = rebuildPlan(emptyState(defaultGoals()));
	persist({ engine });
	return { engine };
}
function persist(store) {
	const tmp = `${STATE_FILE}.tmp`;
	writeFileSync(tmp, JSON.stringify(store.engine, null, 2), "utf8");
	try {
		renameSync(tmp, STATE_FILE);
	} catch {
		writeFileSync(STATE_FILE, JSON.stringify(store.engine, null, 2), "utf8");
	}
}
const store = loadStore();
function fold(events) {
	store.engine = applyEvents(store.engine, events);
	persist(store);
	return store.engine;
}
function recordAttempt(attempt) {
	const date = attempt.date ?? dateIso();
	const block = store.engine.plans[date]?.blocks.find((b) => b.id === attempt.blockId);
	const at = (/* @__PURE__ */ new Date()).toISOString();
	if (block) return fold([{
		type: "task_completed",
		blockId: block.id,
		actualMinutes: attempt.actualMinutes,
		at,
		feedback: {
			energy: attempt.energy,
			difficulty: attempt.difficulty,
			focus: attempt.focus,
			note: attempt.note
		}
	}]);
	return store.engine;
}
function json(res, body, status = 200) {
	res.writeHead(status, {
		"content-type": "application/json; charset=utf-8",
		"access-control-allow-origin": "*"
	});
	res.end(JSON.stringify(body));
}
async function readBody(req) {
	const chunks = [];
	for await (const c of req) chunks.push(c);
	const text = Buffer.concat(chunks).toString("utf8");
	if (!text) return {};
	try {
		return JSON.parse(text);
	} catch {
		return {};
	}
}
function parseMiniIntake(text) {
	const sentences = text.split(/(?<=[.!?])\s+|\n|(?:and then)/i).map((s) => s.trim()).filter(Boolean);
	const out = [];
	for (const s of sentences) {
		if (!s) continue;
		const minutes = /(\d+)\s*min(?:s)?\b/i.exec(s)?.[1];
		const hours = /(\d+(?:\.\d+)?)\s*(?:h|hr|hour)s?\b/i.exec(s)?.[1];
		const duration = minutes ? Number(minutes) : hours ? Math.max(10, Math.round(Number(hours) * 60)) : 30;
		const prioRaw = /\bP([1-3])\b/i.exec(s)?.[1];
		const priority = prioRaw ? Number(prioRaw) : 2;
		const deadline = /(?:by|before|due)\s+(\d{4}-\d{2}-\d{2})/i.exec(s)?.[1];
		const title = s.replace(/\(?(\d+)\s*min(?:s)?\b\)?/gi, "").replace(/\(?(\d+(?:\.\d+)?)\s*(?:h|hr|hours?)\b\)?/gi, "").replace(/\bP([1-3])\b/gi, "").replace(/(?:by|before|due)\s+\d{4}-\d{2}-\d{2}/gi, "").replace(/\s+/g, " ").replace(/^[,.;:\s]+|[,.;:\s]+$/g, "").trim();
		if (!title) continue;
		out.push({
			title,
			durationMinutes: Math.min(480, Math.max(10, duration)),
			priority,
			deadline
		});
	}
	return out;
}
function route(req, res, pathname) {
	const path = pathname.replace(/\/+$/, "") || "/";
	if (req.method === "GET" && path === "/") {
		if ((req.headers.accept ?? "").includes("text/html")) {
			res.writeHead(200, { "content-type": "text/plain; charset=utf-8" });
			res.end([
				"Stone* Planner engine  v1",
				`date ${dateIso()}`,
				`goals ${store.engine.goals.length} · attempts ${store.engine.attempts.length}`,
				`GET  /api/planner/state`,
				`POST /api/planner/replan`,
				`POST /api/planner/feedback`,
				`POST /api/planner/intake`
			].join("\n"));
			return;
		}
		json(res, {
			ok: true,
			status: statusOf(store.engine, dateIso())
		});
		return;
	}
	if (req.method === "GET" && path === "/api/planner/state") {
		json(res, {
			ok: true,
			version: 1,
			data: store.engine
		});
		return;
	}
	if (req.method === "POST" && path === "/api/planner/replan") {
		readBody(req).then((body) => {
			json(res, {
				ok: true,
				version: 1,
				data: fold(body.events ?? [])
			});
		});
		return;
	}
	if (req.method === "POST" && path === "/api/planner/feedback") {
		readBody(req).then((body) => {
			const attempt = body.attempt;
			if (!attempt || !attempt.blockId) {
				json(res, {
					ok: false,
					error: "No attempt payload."
				}, 400);
				return;
			}
			json(res, {
				ok: true,
				version: 1,
				data: recordAttempt(attempt)
			});
		});
		return;
	}
	if (req.method === "POST" && path === "/api/planner/intake") {
		readBody(req).then((body) => {
			const parsed = parseMiniIntake(String(body.text ?? ""));
			if (!parsed.length) {
				json(res, {
					ok: false,
					error: "Could not parse tasks. Try: 'review notes 40min P1 by 2026-09-05'."
				}, 400);
				return;
			}
			const now = /* @__PURE__ */ new Date();
			json(res, {
				ok: true,
				version: 1,
				data: fold(parsed.map((t) => ({
					type: "urgent_add",
					goal: makeAdHocGoal(t, now),
					at: now.toISOString()
				}))),
				added: parsed
			});
		});
		return;
	}
	json(res, {
		ok: false,
		error: `No route for ${path}`
	}, 404);
}
createServer((req, res) => {
	try {
		route(req, res, req.url?.split("?")[0] ?? "/");
	} catch (e) {
		json(res, {
			ok: false,
			error: e instanceof Error ? e.message : "internal error"
		}, 500);
	}
}).listen(PORT, HOST, () => {
	const state = store.engine;
	const today = dateIso();
	const day = state.plans[today] ?? planDay({
		date: today,
		goals: state.goals,
		behavior: state.behavior
	});
	console.log("\n  Stone* Planner engine  (v1)");
	console.log("  -----------------------------");
	console.log("  listening  http://" + HOST + ":" + PORT);
	console.log("  state file " + STATE_FILE);
	console.log("  goals: " + state.goals.length + " · plans: " + Object.keys(state.plans).length + " · attempts: " + state.attempts.length);
	console.log("  today: " + day.blocks.length + " blocks · next: " + (state.nextActions[today] ?? "—"));
	console.log("  -----------------------------");
	console.log("  GET  /api/planner/state      current EngineState");
	console.log("  POST /api/planner/replan     { events: [...] }");
	console.log("  POST /api/planner/feedback   { attempt: {...} }");
	console.log("  POST /api/planner/intake     { text: 'review notes 40min P1' }");
	console.log("  press Ctrl+C to stop\n");
});
//#endregion
export {};
